unit u_couleur;
{
Auteur: Patrick Premartin
Date: 14/11/1991.
Langage: Turbo Pascal 6.0

But: Francisation des noms des 16 couleurs utilisables en mode texte.
}
interface
const
     noir = 0;       gris_sombre = 8;
     bleu = 1;       bleu_clair = 9;
     vert = 2;       vert_clair = 10;
     cyan = 3;       cyan_clair = 11;
     rouge = 4;      rouge_clair = 12;
     magenta = 5;    magenta_clair = 13;
     marron = 6;     jaune = 14;
     gris_clair = 7; blanc = 15;

implementation
end. { Fin de l'unit‚ 'U_Couleur'. }
